"""
Noise generator parameters for Pythonic.

The sound is generated by :mod:`pythonic.voice`; this object only holds the
noise settings (filter, stereo, envelope) that the GUI, presets and
:class:`~pythonic.drum_channel.DrumChannel` read and write.
"""

from enum import Enum

import numpy as np


class NoiseFilterMode(Enum):
    LOW_PASS = 0
    BAND_PASS = 1
    HIGH_PASS = 2


class NoiseEnvelopeMode(Enum):
    EXPONENTIAL = 0  # Natural decay
    LINEAR = 1       # Gated effect
    MODULATED = 2    # Handclap effect


class NoiseGenerator:
    """Noise settings."""

    def __init__(self):
        self.filter_mode = NoiseFilterMode.LOW_PASS
        self.filter_frequency = 20000.0  # Hz (20-20000)
        self.filter_q = 0.707
        self.stereo = False
        self.envelope_mode = NoiseEnvelopeMode.EXPONENTIAL
        self.attack_ms = 0.0
        self.decay_ms = 316.23

    def set_filter_mode(self, mode: NoiseFilterMode):
        self.filter_mode = mode

    def set_filter_frequency(self, freq: float):
        self.filter_frequency = float(np.clip(freq, 20.0, 20000.0))

    def set_filter_q(self, q: float):
        """Filter Q (range 0.1 to 10000)."""
        self.filter_q = float(np.clip(q, 0.0, 10000.0))

    def set_stereo(self, enabled: bool):
        self.stereo = enabled

    def set_envelope_mode(self, mode: NoiseEnvelopeMode):
        self.envelope_mode = mode

    def set_attack(self, attack_ms: float):
        self.attack_ms = float(np.clip(attack_ms, 0.0, 10000.0))

    def set_decay(self, decay_ms: float):
        self.decay_ms = float(np.clip(decay_ms, 1.0, 10000.0))
