"""
Oscillator parameters for Pythonic.

The sound is generated by :mod:`pythonic.voice`; this object only holds the
oscillator settings (waveform, frequency, pitch modulation) that the GUI,
presets and :class:`~pythonic.drum_channel.DrumChannel` read and write.
"""

from enum import Enum

import numpy as np


class WaveformType(Enum):
    SINE = 0
    TRIANGLE = 1
    SAWTOOTH = 2


class PitchModMode(Enum):
    DECAYING = 0  # Exponential pitch decay (classic drum pitch envelope)
    SINE = 1      # Sine LFO / FM modulation
    RANDOM = 2    # Random noise modulation


class Oscillator:
    """Oscillator settings."""

    def __init__(self):
        self.frequency = 440.0  # Hz (20-20000)
        self.waveform = WaveformType.SINE
        self.pitch_mod_mode = PitchModMode.DECAYING
        self.pitch_mod_amount = 0.0  # semitones
        self.pitch_mod_rate = 100.0  # ms in Decay mode, Hz in Sine / Noise mode

    def set_frequency(self, freq: float):
        self.frequency = float(np.clip(freq, 20.0, 20000.0))

    def set_waveform(self, waveform: WaveformType):
        self.waveform = waveform

    def set_pitch_mod_mode(self, mode: PitchModMode):
        self.pitch_mod_mode = mode

    def set_pitch_mod_amount(self, amount: float):
        """Pitch modulation amount in semitones."""
        if self.pitch_mod_mode == PitchModMode.DECAYING:
            self.pitch_mod_amount = float(np.clip(amount, -96.0, 96.0))
        elif self.pitch_mod_mode == PitchModMode.SINE:
            self.pitch_mod_amount = float(np.clip(amount, -48.0, 48.0))
        else:
            # Noise mode: only the magnitude sets the modulation depth
            self.pitch_mod_amount = float(np.clip(abs(amount), 0.0, 20000.0))

    def set_pitch_mod_rate(self, rate: float):
        self.pitch_mod_rate = max(0.001, float(rate))
